engine = "oak"
port = 7180

[[tenants]]
name = "sandbox"
rootPasswd = "demo"
key = "./.config/antbox.key"
jwks = "./.config/antbox.jwks"
storage = ["inmem/inmem_storage_provider.ts"]
repository = ["sqlite/sqlite_node_repository.ts"]
configurationRepository = ["sqlite/sqlite_configuration_repository.ts"]
eventStoreRepository = ["sqlite/sqlite_event_store_repository.ts"]

[tenants.ai]
enabled = false
defaultModel = "google/gemini-2.5-flash"
