engine = "oak"
port = 7180
rootPasswd = "demo"
key = "../antbox.key"
jwks = "../antbox.jwks"

[[tenants]]
name = "sandbox"
storage = ["inmem/inmem_storage_provider.ts"]
repository = ["sqlite/sqlite_node_repository.ts"]
configurationRepository = ["sqlite/sqlite_configuration_repository.ts"]
eventStoreRepository = ["sqlite/sqlite_event_store_repository.ts"]

[tenants.limits]
storage = "pay-as-you-go"
tokens = 0

[tenants.ai]
enabled = false
defaultModel = "google/gemini-2.5-flash"
